[tool.poetry]
name = "tldw"
version = "0.1.0"
description = "Multi-tool for researchers"
authors = ["Robert <contact@rmusser.net>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
